stages:
  - deploy

Deploy:
  stage: deploy
  variables:
    VAR_DIREKTORI: "/var/www/html"
    VAR_GIT_URL_TANPA_HTTP: "git@cicd.optimajasa.co.id:danudenny/poj-web.git"
    VAR_CLONE_KEY: "glpat-TADxzfqM5NP1p6wTr4sf"
    VAR_USER: "deployer"
    VAR_IP: "192.168.100.73"
    VAR_FILE_ENV: $FILE_ENV

  before_script:
    - "which ssh-agent || ( apt-get install openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 23932 $VAR_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh -p 23932 $VAR_USER@$VAR_IP "git config --global safe.directory '*'"
    - ssh -p 23932 $VAR_USER@$VAR_IP "cd $VAR_DIREKTORI && git pull origin staging && exit"
    - ssh -p 23932 $VAR_USER@$VAR_IP "if [ -d $VAR_DIREKTORI/.env ]; then rm .env; fi"
    - ssh -p 23932 $VAR_USER@$VAR_IP "cd $VAR_DIREKTORI && echo '$VAR_FILE_ENV' >> .env"
    - ssh -p 23932 $VAR_USER@$VAR_IP "composer install --ignore-platform-reqs"
    - ssh -p 23932 $VAR_USER@$VAR_IP "php artisan migrate"
    - ssh -p 23932 $VAR_USER@$VAR_IP "php artisan key:generate"
    - ssh -p 23932 $VAR_USER@$VAR_IP "npm run build"
    - echo "A!"
  only:
    - tags
