stages:
  - test

before_script:
  - echo "$VPN_PASSWORD" "${VPN_PASSWORD}" $VPN_PASSWORD ${VPN_PASSWORD}

test:
  stage: test
  script:
    - echo "$VPN_PASSWORD" "$VPN_USERNAME" "$VPN_SERVER_ADDRESS"
  only:
    - staging
    - tags
