stages:
  - deploy

Deploy:
  image: tetraweb/php
  stage: deploy
  variables:
    VAR_DIREKTORI: "/var/www/html"
    VAR_GIT_URL_HTTPS: "https://danudenny:glpat-K9-cPQe3oCyzpySEJRjx@cicd.optimajasa.co.id/danudenny/poj-web.git"
    VAR_USER: "deployer"
    VAR_IP: "192.168.100.73"
    VAR_FILE_ENV: $FILE_ENV

  before_script:
    - "which ssh-agent || ( apt-get install openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 23932 $VAR_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - git config --global credential.helper "store --file ~/.git-credentials"
    - echo -e "https://danudenny:glpat-K9-cPQe3oCyzpySEJRjx\n" > ~/.git-credentials
    - if [ ! -d /var/www/html ]; then git clone $VAR_GIT_URL_HTTPS /var/www/html; else cd /var/www/html && git pull origin staging; fi
    - git config user.name "Denny Danuwijaya"
    - git config user.email "danudenny@gmail.com"
    - git pull origin staging
    - rm ~/.git-credentials
    - cd $VAR_DIREKTORI && echo '$VAR_FILE_ENV' >> .env
    - ssh -p 23932 $VAR_USER@$VAR_IP "cd $VAR_DIREKTORI && echo '$VAR_FILE_ENV' >> .env"
    - ssh -p 23932 $VAR_USER@$VAR_IP "composer install --ignore-platform-reqs"
    - ssh -p 23932 $VAR_USER@$VAR_IP "php artisan migrate"
    - ssh -p 23932 $VAR_USER@$VAR_IP "php artisan key:generate"
    - ssh -p 23932 $VAR_USER@$VAR_IP "npm install"
    - ssh -p 23932 $VAR_USER@$VAR_IP "npm run build"
    - echo "A!"
  only:
    - tags
