before_script:
  - echo "Before script"
  - cd /var/www/html
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin staging
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R atten:www-data /var/www/html/
    - find /var/www/html -type f -exec chmod 664 {} \;
    - find /var/www/html -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart