services:
  - name: docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose up -d
    - docker run --rm poj-web-app chmod -R 777 storage bootstrap/cache
