version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - COMPOSER_ALLOW_SUPERUSER=1
    container_name: app
    depends_on:
      - db-master
      - db-slave
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - backend
      - frontend

  db-master:
    image: postgres:13
    container_name: db-master
    environment:
      - POSTGRES_PASSWORD=masterpass
    restart: unless-stopped
    ports:
        - "5434:5432"
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - backend

  db-slave:
    build:
        context: .
        dockerfile: pg.Dockerfile
    image: postgres-replica
    container_name: db-slave
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=slavepass
    ports:
      - "5433:5432"
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "82:80"
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend

volumes:
  db_data:

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
