version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - COMPOSER_ALLOW_SUPERUSER=1
    container_name: app
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - backend
      - frontend

  nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
          - "82:80"
      restart: unless-stopped
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
          - frontend

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
