version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - COMPOSER_ALLOW_SUPERUSER=1
    container_name: app
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - backend

networks:
    backend:
        driver: bridge
